[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepConfigByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.htpasswd",
"accounts\\.v4"]
Triage = "Red"