[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayPPKForContentScan"
MatchAction = "Relay"
RelayTargets = ["KeepUnencryptedPPK"]
Description = "PPK files are relayed to content scanning for unencrypted detection"
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.ppk"]
Triage = "Green"
